# =============================================================================
# nWave Documentation Dependency Map
# =============================================================================
# Defines dependency relationships between source configurations and derived
# documentation. Used by pre-commit validation to enforce consistency.
#
# Structure:
#   - tracked_files: List of files with version fields that participate in tracking
#   - validation_rules: Validation behavior configuration
#   - version_strategy: Versioning approach and comparison logic
# =============================================================================

version: "1.1.0"
description: "Dependency tracking for nWave framework documentation consistency (5-layer testing)"

# -----------------------------------------------------------------------------
# Tracked Files
# -----------------------------------------------------------------------------
# Files with version fields that participate in dependency tracking

tracked_files:
  # Source: Framework catalog (primary configuration)
  - path: "nWave/framework-catalog.yaml"
    version_format: "yaml"
    version_field: "version"
    description: "Primary framework configuration - commands, agents, workflows"

    triggers_update:
      - file: "README.md"
        sections:
          - id: "command-reference"
            location: "~lines 30-50"
            description: "Command list and usage examples"
            source: "framework-catalog.yaml:commands"
          - id: "agent-overview"
            location: "~lines 86-93"
            description: "Agent counts and wave assignments"
            source: "framework-catalog.yaml:agents"
        reason: "Command descriptions and agent metadata must match catalog"

      - file: "nWave/data/agents_reference/COMMAND-AGENT-MAPPING.md"
        sections:
          - id: "full-document"
            location: "entire file"
            description: "Complete command-agent mapping table"
            source: "framework-catalog.yaml:commands,agents"
        reason: "Mapping document is fully derived from catalog"

  # Source: Build configuration
  - path: "tools/build_config.yaml"
    version_format: "yaml"
    version_field: "version"
    description: "IDE bundle builder configuration"

    triggers_update:
      - file: "README.md"
        sections:
          - id: "installation"
            location: "~lines 17-28"
            description: "Installation instructions and script usage"
            source: "build_config.yaml:build,output"
        reason: "Build instructions must match configuration"

  # Terminal: Root documentation
  - path: "README.md"
    version_format: "markdown_comment"
    version_pattern: "<!-- version: {version} -->"
    description: "Primary project documentation"
    triggers_update: []  # Terminal node - no downstream dependencies

  # Terminal: Command-agent reference
  - path: "nWave/data/agents_reference/COMMAND-AGENT-MAPPING.md"
    version_format: "markdown_comment"
    version_pattern: "<!-- version: {version} -->"
    description: "Auto-generated command-agent mapping reference"
    triggers_update: []  # Terminal node - regenerated from catalog

  # Documentation: nWave framework README
  - path: "nWave/README.md"
    version_format: "markdown_comment"
    version_pattern: "<!-- version: {version} -->"
    description: "nWave framework overview and methodology documentation"
    triggers_update: []  # Terminal node - should match framework-catalog.yaml version

  # Documentation: Scripts directory README
  - path: "scripts/README.md"
    version_format: "markdown_comment"
    version_pattern: "<!-- version: {version} -->"
    description: "Scripts directory structure and usage documentation"
    triggers_update: []  # Terminal node - update when script structure changes

  # Documentation: Installation scripts README
  - path: "scripts/install/README.md"
    version_format: "markdown_comment"
    version_pattern: "<!-- version: {version} -->"
    description: "Installation scripts comprehensive documentation"
    triggers_update: []  # Terminal node - update when install scripts change

  # Documentation: Build tools README
  - path: "tools/README.md"
    version_format: "markdown_comment"
    version_pattern: "<!-- version: {version} -->"
    description: "Build and IDE bundling tools documentation"
    triggers_update: []  # Terminal node - should match build_config.yaml version

  # Documentation: Hooks README
  - path: "nWave/hooks/README.md"
    version_format: "markdown_comment"
    version_pattern: "<!-- version: {version} -->"
    description: "Pre-commit hooks and validation documentation"
    triggers_update: []  # Terminal node - update when hooks change

  # Documentation: Archived scripts README
  - path: "scripts/archive/README.md"
    version_format: "markdown_comment"
    version_pattern: "<!-- version: {version} -->"
    description: "Archived and legacy scripts documentation"
    triggers_update: []  # Terminal node - rarely changes

  # =============================================================================
  # DIVIO-Restructured Documentation (Version: **Version**: X.Y.Z format)
  # =============================================================================

  # How-to Guide: Invoking Reviewers
  - path: "docs/guides/how-to-invoke-reviewers.md"
    version_format: "markdown_header"
    version_pattern: "**Version**: {version}"
    description: "How-to guide for invoking Layer 4 peer review agents"
    triggers_update: []  # Terminal node - should match framework-catalog.yaml version

  # Reference: Reviewer Agents
  - path: "docs/reference/reviewer-agents-reference.md"
    version_format: "markdown_header"
    version_pattern: "**Version**: {version}"
    description: "Reference documentation for all reviewer agent specifications"
    triggers_update: []  # Terminal node - should match framework-catalog.yaml version

  # Reference: Layer 4 API
  - path: "docs/reference/layer-4-api-reference.md"
    version_format: "markdown_header"
    version_pattern: "**Version**: {version}"
    description: "API contracts, interfaces, and configuration reference for Layer 4"
    triggers_update: []  # Terminal node - should match framework-catalog.yaml version

  # How-to Guide: Layer 4 for Developers
  - path: "docs/guides/layer-4-for-developers.md"
    version_format: "markdown_header"
    version_pattern: "**Version**: {version}"
    description: "Programmatic integration guide for developers"
    triggers_update: []  # Terminal node - should match framework-catalog.yaml version

  # How-to Guide: Layer 4 for Users
  - path: "docs/guides/layer-4-for-users.md"
    version_format: "markdown_header"
    version_pattern: "**Version**: {version}"
    description: "Manual workflow guide for CLI users"
    triggers_update: []  # Terminal node - should match framework-catalog.yaml version

  # How-to Guide: Layer 4 for CI/CD
  - path: "docs/guides/layer-4-for-cicd.md"
    version_format: "markdown_header"
    version_pattern: "**Version**: {version}"
    description: "Pipeline integration guide for CI/CD systems"
    triggers_update: []  # Terminal node - should match framework-catalog.yaml version

  # Reference: nWave Commands
  - path: "docs/reference/nwave-commands-reference.md"
    version_format: "markdown_header"
    version_pattern: "**Version**: {version}"
    description: "Complete command reference for nWave workflow"
    triggers_update: []  # Terminal node - should match framework-catalog.yaml version

  # DIVIO Analysis: Classification Report (YAML)
  - path: "docs/analysis/divio-audit/DOCUMENTATION_CLASSIFICATION_REPORT.yaml"
    version_format: "yaml"
    version_field: "version"
    description: "DIVIO classification analysis of all documentation"
    triggers_update: []  # Analysis artifact - version tracks framework alignment

  # DIVIO Analysis: Classification Summary
  - path: "docs/analysis/divio-audit/DIVIO_CLASSIFICATION_SUMMARY.md"
    version_format: "markdown_header"
    version_pattern: "**Version**: {version}"
    description: "Executive summary of DIVIO classification results"
    triggers_update: []  # Analysis artifact - version tracks framework alignment

  # DIVIO Analysis: Restructuring Action Plan
  - path: "docs/analysis/divio-audit/DOCUMENTATION_RESTRUCTURING_ACTION_PLAN.md"
    version_format: "markdown_header"
    version_pattern: "**Version**: {version}"
    description: "Detailed implementation guide for documentation restructuring"
    triggers_update: []  # Analysis artifact - version tracks framework alignment

  # DIVIO Analysis: Completion Summary
  - path: "docs/analysis/divio-audit/DOCUMENTARIST_ANALYSIS_COMPLETE.md"
    version_format: "markdown_header"
    version_pattern: "**Version**: {version}"
    description: "Summary of documentarist analysis completion"
    triggers_update: []  # Analysis artifact - version tracks framework alignment

# -----------------------------------------------------------------------------
# Validation Rules
# -----------------------------------------------------------------------------

validation_rules:
  # Require version bump when file content changes (excluding whitespace)
  require_version_bump_on_change: true

  # Enforce dependent versions >= source version
  enforce_downstream_version_sync: true

  # Allow dependents to have higher versions (manual updates permitted)
  allow_dependent_ahead: true

  # Ignore whitespace-only changes
  ignore_whitespace_changes: true

  # Block commits with invalid version formats
  block_invalid_version_format: true

# -----------------------------------------------------------------------------
# Version Strategy
# -----------------------------------------------------------------------------

version_strategy:
  format: "semver"  # Semantic versioning (MAJOR.MINOR.PATCH)
  comparison: "semver_compare"  # Use semantic version comparison

  # Version increment guidance
  increment_guidance:
    major: "Breaking changes, incompatible API changes"
    minor: "New features, backward-compatible additions"
    patch: "Bug fixes, documentation corrections"
